import streamlit as st

st.title('NP_Synthesis')
st.write('''
0                    chem_synthesis by silver nitrate''')

st.write('''1               chem_synthesis_reduction_by_D_maltose''')
st.write('''2                    green_synthesis  by Bacillus sp.''')
st.write('''3           green_synthesis  using fungus Trichoderma''')
st.write('''4            green_synthesis by Klebsiella pneumoniae''')
st.write('''5     green_synthesis from fungus  Aspergillus flavus''')
st.write('''6   green_synthesis from fungus  Phytophthora infe...''')
st.write('''7      green_synthesis from fungus Trichoderma viride''')
st.write('''8   green_synthesis using C. zylinicum aqueous ext...''')
st.write('''9   green_synthesis using Dioscorea bulbifera tube...''')
st.write('''10               green_synthesis using Ulva fasciata ''')
st.write('''11  green_synthesis using Withania coagulans fruit...''')
st.write('''12  green_synthesis using extract of Klebsiella pn...''')
st.write('''13  green_synthesis using extract of acinetobacter...''')
st.write('''14       green_synthesis using extract of corn leaves
''')

st.title('genus')

st.write('0      Acinetobacter')
st.write('1     Actinobacillus')
st.write('2           Bacillus')
st.write('3            Candida')
st.write('4   Candida glaebosa')
st.write('5       Enterococcus')
st.write('6        Escherichia')
st.write('7        Haemophilus')
st.write('8         Klebsiella')
st.write('9           Listeria')
st.write('10       Micrococcus')
st.write('11      Nakaseomyces')
st.write('12         Neisseria')
st.write('13       Pasteurella')
st.write('14           Proteus')
st.write('15       Pseudomonas')
st.write('16        Salmonella')
st.write('17          Serratia')
st.write('18    Staphylococcus')
st.write('19     Streptococcus')
st.write('20            Vibrio')